@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.chen1335.immersiveMechanical.attachmentDatas;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;