org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

parchment_minecraft_version=1.21
parchment_mappings_version=2024.07.28
minecraft_version=1.21.1
minecraft_version_range=[1.21.1, 1.22)
neo_version=21.1.220
neo_version_range=[21.1.0,)
loader_version_range=[4,)
kubejs_version=2101.7.2-build.368

## Mod Properties
mod_id=immersive_mechanical
mod_name=Immersive Mechanical
mod_license=ch1335's custom license in GitHub
mod_version=2101.0.0-pre6
mod_group_id=com.chen1335.immersiveMechanical
mod_authors=chen_1335
mod_description=more mechanical!.
