@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.chen1335.immersiveMechanical.common.blocks.multiblocks.logic.industrialFurnace;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;