@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package com.chen1335.immersiveMechanical.recipe;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;